### ISSUE TITLE
Update old incompatible code in statemanager, roverprocess and main to python 3

### ISSUE THREAD

**Issue by ausshir** [UofSSpaceDesignTeam/rover-software#14]
Only goal is the code needs to not crash when you do a pull request! Doesn't have to do anything fun.

- [x] main
- [x] satemanager
- [x] roverprocess
- [ ] Brag that we have updated to the most cutting edge standards!

May want to put this on the same branch as the server updating branch.

**Comment by ottopasuuna** [comment]
I got the core rover running in python 3. Just fixed the print statements, a few changes with the semantics of including modules, and stopping the ReceiverThread in the RoverProcess.
Is this ready for a pull request, or should we wait until things like the CAN server are ported as well?

**Comment by ausshir** [comment]
I did it last night too with the standard 2to3 script in tools. Does yours crash on closing?

**Comment by ausshir** [comment]
Also I'd keep this branch open until the end of the milestone

**Comment by ottopasuuna** [comment]
No it doesn't crash; it looks like python 3 depreciated `thread._Thread__stop()` so I changed the cleanup method to use join() instead.

**Comment by ausshir** [comment]
Great! We'll hold onto this branch and see if we can port the servers or rewrite them. Would you be able to do a brief writeup on what you did for the wiki for future reference?

**Comment by ottopasuuna** [comment]
Sure. Should I just make a new page called Porting to Python 3 or something like that?

**Comment by ausshir** [comment]
Yeah whatever you like - you may want to create some sections. (This is more so for issue #9)
